name: Build Project

on:
  pull_request:
    branches:
      - 'develop'
      - 'staging'
      - 'main'

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm build
