name: Pull request into develop, staging, main

on:
  pull_request:
    branches:
      - "develop"
      - "staging"
      - "main"

jobs:
  install-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node modules
        run: npm ci

      - name: Lint Check
        run: npm run lint

      - name: Lint Check
        run: npm run prettier:check

      - name: Code Coverage
        run: npm run test:coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: Upload reports to codecov
          fail_ci_if_error: true
          verbose: true
      - run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          find . -iregex "codecov.*"
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}

  build:
    needs: install-and-format
    uses: ./.github/workflows/build.yaml
