name: Pull request into develop, staging, main

on:
  pull_request:
    branches:
      - "develop"
      - "staging"
      - "main"

jobs:
  install-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node modules
        run: npm ci

      - name: Lint Check
        run: npm run lint

      - name: Lint Check
        run: npm run prettier:check
